"""
API ERROR_CODE Constants

"""

NORMAL = 0
UNKNOWN_ERROR = 2
COOKIE_EXPIRED = 3
ACCESS_RIGHT_ERROR = 4
MISSING_ARGUMENT = 5
NO_FILE_UPLOAD = 6
UPLOAD_ERROR = 7
API_INTERNAL_ERROR = 10

JOB_NOT_EXISTS = 8
PARAMETERS_INVALID = 11
IP_NOT_IN_SETTING_LIST = 12
EXCEL_FORMAT_ERROR = 13
EXCEL_PARSE_ERROR = 14
EXCEL_CREATE_ERROR = 15
EXCEL_APPEND_ERROR = 16
EXCEL_REPLACE_ERROR = 17
EXCEL_DELETE_ERROR = 18
EXCEL_NOT_EXISTS = 19
EXCEL_TB_SCHEMA_NOT_MATCH = 20
EXCEL_TB_OCCUPIED = 21
CSV_FILE_ENCODE_NOT_SUPPORT = 22
CSV_FILE_ENCODE_SUPPORT_UTF8_GBK = 23

DB_CREATE_ERROR = 100
DS_DELETE_ERROR = 101
DS_NOT_EXISTS = 102
DB_EXISTS = 103
DS_CONN_ERROR = 104
UNSUPPORTED_DS_TYPE = 105
DS_SYNC_ERROR = 106

TASK_EXEC_ERROR = 200
TB_INFO_ERROR = 3216


CAPACITY_OVERRUN_ERROR = 4000
